
const HOURS_IN_DAY = 24;
const MILLISECONDS_IN_MINUTE = 60000;
const SECONDS_IN_MINUTE = 60;
const MINUTES_IN_HOUR = 60;
export {HOURS_IN_DAY,MILLISECONDS_IN_MINUTE,SECONDS_IN_MINUTE,MINUTES_IN_HOUR};
